name: Generate Snake Animation

on:
  schedule: # Runs at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake.svg and snake.gif
        uses: Platane/snk@v3
        with:
          github_user_name: aakarshitpathak
          outputs: |
            dist/snake.svg
            dist/snake.gif
          # Slower snake settings
          palette: github-dark
          color_snake: "#39FF14"
          frame_duration: 150  # default is 100 → higher = slower
          steps: 4             # more steps = smoother + slower

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
